### ISSUE TITLE
Introduce `mongo db`

### ISSUE THREAD

**Issue by minkj1992** [Nexters/myply#8]
`google cloud sql` is not suitable for side-project because a pricing issue.

> No matter how I reduced cloud sql spec, the minimum `cloud sql` price is `$8.56`/ per month.

Therefore, I consider `firestore`(nosql) which provides free specs up to a certain request.

- TODO
  - [x] Checks [golang firestore client](https://pkg.go.dev/cloud.google.com/go/firestore)
  - [x] Checks firestore db schema migration system.
  - [x] Applies DI with wire on myply' /infrastructure/client/firestore.
  - [x] Updates CICD pipeline and deprecate `cloud sql` on gcp.

**Comment by minkj1992** [comment]
Todo
  - Change schema if we pick NOSQL
  - Compare firestore vs mongodb vs redis
  - Writes "Does redis can be a primarily databse?", focused on duarability and deploy and schema versioning.
  - Compare free tier cloud database
    - firestore: 1gb in gcp
    - mongo: 512mib in atlas
    - redis: There are no suitable & reasonable SaaS service, we should make redis db server with naver cloud computer.

**Comment by minkj1992** [comment]
Picked mongo

![Uploading Screenshot_20220710-232821_KakaoTalk.jpg…]()

**Comment by minkj1992** [comment]
In conclusion, we picked
- Mongo as primary databse
  - schema: tags, memos, users 
- Redis for cache
  - rank search keywords
  - cache youtube search and retrieve api response

**Comment by minkj1992** [comment]
- deploy
  - [atlas with cloud run](https://cloud.google.com/blog/topics/developers-practitioners/serverless-with-cloud-run-mongodb-atlas?hl=en_US&_ga=2.229773333.863985093.1657507187-950552380.1656129965&_gac=1.258489848.1657162155.Cj0KCQjw5ZSWBhCVARIsALERCvw6sE4d5chw17EZYkmQE2CqZAsDudd3GvacGWXr6DNFgQUztLDYIAQaAueEEALw_wcB)
  - [Connect from the Atlas CLI](https://www.mongodb.com/docs/atlas/cli/stable/connect-atlas-cli/#take-the-next-steps)
  - [cloud run with atlas](https://cloud.google.com/community/tutorials/serverless-vpc-access-private-mongodb-atlas)

- mongo with golang
  - [fiber recipe](https://github.com/gofiber/recipes/blob/master/mongodb/main.go)
  - [mongo with golang](https://www.mongodb.com/docs/drivers/go/current/quick-start/#add-mongodb-as-a-dependency)

**Comment by minkj1992** [comment]
https://www.bespinglobal.com/serverless-vpc/

**Comment by mcauto** [comment]
@minkj1992 [bolt](https://github.com/boltdb/bolt)나 [rqlite](https://github.com/rqlite/rqlite)를 사용해보는 건 어때요?

**Comment by minkj1992** [comment]
> @minkj1992 [bolt](https://github.com/boltdb/bolt)나 [rqlite](https://github.com/rqlite/rqlite)를 사용해보는 건 어때요?

Wow thanks master. I have questions.


1. I'm new to bolt or rqlite, can I use it in a serverless environment like cloud run?

2. If you have used either of them, is there any advantage compared to redis? (maybe price?)

**Comment by mcauto** [comment]
> > @minkj1992 [bolt](https://github.com/boltdb/bolt)나 [rqlite](https://github.com/rqlite/rqlite)를 사용해보는 건 어때요?
> 
> Wow thanks master. I have questions.
> 
> 1. I'm new to bolt or rqlite, can I use it in a serverless environment like cloud run?
> 2. If you have used either of them, is there any advantage compared to redis? (maybe price?)

1. I like to make MVP(Minimum Viable Product) with a small instance (vm) rather than developing it with serverless (aws Lambda, gcp function).
This is because serverless is cloud platform dependent, but not instance (vm).

2. It's similar to [this opinion](https://github.com/minkj1992/minkj1992.github.io/issues/6#issuecomment-1180142042)
and I recommend that you read this link - https://news.ycombinator.com/item?id=10880652
